Portfolio page Mobile Version Skeleton Card and About Section
henrycode460/Portfolio-Mobile-Version-Skeleton pull request #2
Opened 2022-04-22 10:04 UTC by henrycode460

2022-04-22 11:54 UTC, MeqdamAlqudah requested changes
Hi @henrycode460 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://media1.giphy.com/media/RcZlXVml8oKtoGQeqe/200w.webp?cid=ecf05e47z083k5rvt5gt35uxdtfj7rl06lyu1jrbiku4peys&rid=200w.webp&ct=g)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 11:54 UTC, MeqdamAlqudah commented on index.html
> +            <li class="workInfoDetails first-work"><a class="workInfoDetailsLink firstWorkLink" href="#">CANOPY</a> <img class="counter" src="Counter.svg" alt=""> </li>
- [ ] Please fix the aligning of each project use flexbox to align each one of them 
![image](https://user-images.githubusercontent.com/74744787/164703112-8e701d8e-d2b8-4663-976a-57d2b64e8f19.png)

- Your design doesn't look like [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) design)

| Your design | Figma design |
| ------------- | --------------- |
| ![image](https://user-images.githubusercontent.com/74744787/164703403-8d66592f-09d2-4aaa-9c9f-e0d8bd82f04d.png) | ![image](https://user-images.githubusercontent.com/74744787/164703481-b20054dc-fcc9-4aa2-85c7-0026cb410f63.png) |
| look at this weird doubling in the card please fix it | |

2022-04-22 11:54 UTC, MeqdamAlqudah commented on index.html
> +        <button type="button"  class="btnNormal">See Project</button>
- [ ] Please fix margins (top, bottom, left, right) defined in the design

| Your design | Figma design |
| ------------- | --------------- |
| ![image](https://user-images.githubusercontent.com/74744787/164705285-603ae00a-875e-4f62-9e70-96152e779d65.png) | ![image](https://user-images.githubusercontent.com/74744787/164705377-767bfc11-f62f-42e8-b87c-bd9dc8a0f312.png) |

2022-04-22 11:54 UTC, MeqdamAlqudah commented on index.html
> +            <h2 class="intro">
- [ ] Please use the same font family as in Figma design in Figma design they used Poppins for each card title and paragraph
![image](https://user-images.githubusercontent.com/74744787/164705747-94ae32c0-e29c-4b41-ad2f-a35f83e96aef.png)

2022-04-22 11:54 UTC, MeqdamAlqudah commented on index.html
> +
- [ ] Please use the same font family used in the Figma design 

| Your design | Figma design |
| ------------- | --------------- |
| ![image](https://user-images.githubusercontent.com/74744787/164706437-ad3bd6b0-3a8a-4825-a9d4-6c204d7fefdf.png) | ![image](https://user-images.githubusercontent.com/74744787/164706500-dd379349-d7bd-4a4f-97a0-7a065c26f8f0.png) |

I noticed you didn't use the same font family to design the paragraph and the title of this section

2022-04-22 11:54 UTC, MeqdamAlqudah commented on index.html
> +                    </a>
- [ ] Please fix this weird line here and make it look like the design 

| Your design | Figma design |
| ------------- | --------------- |
| ![image](https://user-images.githubusercontent.com/74744787/164707302-27c69bb1-605b-4574-a52b-8e9858e5813a.png) | ![image](https://user-images.githubusercontent.com/74744787/164707371-356901c2-9b69-453b-95e9-8a02d95ea3d4.png) |

2022-04-22 11:54 UTC, MeqdamAlqudah commented on index.html
> +
- [ ] Please apply the hovering on the get my resume button 

![image](https://user-images.githubusercontent.com/74744787/164707680-13ad4cc7-f4f4-49d3-96c8-a365a80bf33c.png)
![image](https://user-images.githubusercontent.com/74744787/164707752-8d0e81ca-88e2-4fa0-a95a-1240253890a9.png)

2022-04-22 11:54 UTC, MeqdamAlqudah commented on index.html
> +                    <a class="" href="#"><img class="language-display-icon" src="lanDisplayIcon.svg" alt=""></a>
- [ ] Please align the items in the language , frameworks , sections with flex box and make sure they looks exactly like Figma design 



| Your design | Figma |
| ------------- | ------- | 
| ![image](https://user-images.githubusercontent.com/74744787/164708340-f439e6e5-ec95-4ec6-8e1c-bf4b9720d1b7.png) | ![image](https://user-images.githubusercontent.com/74744787/164708419-ec6a7341-57e7-4ddb-85db-7af17c12e4bb.png) |

Please fix the arrows here and make sure that the distance between the arrow and the title is the same as in Figma design

2022-04-23 17:21 UTC, roshan-bajgain approved these changes
# Approved 👏 

Hi there, 

<img src="https://media1.giphy.com/media/obN7DdnUWxuyqz5qZS/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

To Highlight: 
- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error at present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2022-04-23 18:09 UTC, merged