Portfolio Page Desktop version
henrycode460/Portfolio-Mobile-Version-Skeleton pull request #5
Opened 2022-04-28 10:34 UTC by henrycode460

Added media Query for Desktop Version
-Added media query to create a desktop version of the portfolio page

2022-04-28 11:13 UTC, AnselemOdims requested changes
### Hi @henrycode460 , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-28 11:13 UTC, AnselemOdims commented on index.html
> +            <a class="langIconDetailsLink" href="#"
- [ ] Please kindly ensure that the language(HTML, CSS, JS)  icons are the same size as the original design. At the moment, yours is looking too big.

### Your Design 
![image](https://user-images.githubusercontent.com/43995830/165737604-ce88543d-fb1a-49cd-b2b5-1d5e3679570d.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/165738225-967240e3-184d-4c4a-b8e8-40e3bc174d5f.png)

2022-04-28 11:13 UTC, AnselemOdims commented on index.html
> +                  <button type="submit" class="btnNormal">See Project</button>
- [ ] Please ensure that the styling for the button state interactions are implemented according to the design

![image](https://user-images.githubusercontent.com/43995830/165738406-b9e9d751-7e60-48c1-a331-b4a679833f3a.png)

2022-04-28 11:13 UTC, AnselemOdims commented on index.html
> +      </nav>
- [ ] Good job implementing the desktop design, but it seems some of the mobile designs were affected in the process. Please ensure that both mobile and desktop designs align with the original design. In this case, your navbar and headline sections does not match the design.

### Your Design
![image](https://user-images.githubusercontent.com/43995830/165739104-58aef7c3-e1b0-436d-aabd-5226048d510c.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/165739282-2072c4f8-7612-434d-a617-cabe4f11cbdc.png)

2022-04-28 11:13 UTC, AnselemOdims commented on index.html
> +            <a class="workInfoDetailsLink" href="#">2015</a>
- [ ] Good job implementing the desktop design, but it seems some of the mobile designs were affected in the process. In this case, your project cards does not match the original design. Please ensure that both mobile and desktop designs align with the original design. 

### Your Design
![image](https://user-images.githubusercontent.com/43995830/165739441-4f309391-52d7-4f55-b6ee-ee390eb93b3f.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/165739540-15098176-5675-4735-ae5a-1ce0b6f59652.png)

2022-04-28 11:21 UTC, henrycode460 commented on style.css
> +  }
@AnselemOdims Kindly observe that the style in the mobile version in figma is not the same as in the mobile. There are different images , different content , different navigation , etc.

2022-04-28 12:18 UTC, henrycode460 commented on style.css
> +  }
@[](url
![Screenshot (78)](https://user-images.githubusercontent.com/96744031/165750109-429c945b-8e3f-4eb5-b1c4-0a0dfdf3a964.png)
![Screenshot (79)](https://user-images.githubusercontent.com/96744031/165750121-9ff605d0-1683-4ea6-b80d-3f1f03003d35.png)
)

image different from the one in the mobile version. 
![Screenshot (80)](https://user-images.githubusercontent.com/96744031/165750370-fee20781-1c80-4424-b64c-535625fa8702.png)

2022-04-29 08:37 UTC, gtekle requested changes
Hi @henrycode460 :wave: , 

Good job so far! 
There are some issues that you still need to work on to go to the next project but you are almost there! (Please DM me on Slack before you start working on this changes)


## Highlights

## Required Changes ♻️
_Check the comments under the review._

- [ ] I see that you have duplicated your works section HTML code (one for mobile and one for desktop). You should not duplicate your HTML code for different screen sizes. The only thing you need to add is a media query `css` styling targeting different screen sizes. (`min-width: 768px` for desktop version in this case)

- [ ] In the works section, it was a requirement to use Flexbox to layout the contents of the project card in the previous milestones. However, you manually swapped the image and project details on every other card instead of using `css` Flexbox `order` property. As a result, it is now difficult to make your works section responsive using CSS styling. Please take a look at [this](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Ordering_Flex_Items) tutorial.
![works-section-800px](https://user-images.githubusercontent.com/44057863/165910467-880a6f95-c55b-4d6e-907e-23ec8a9d3a85.png)


- [ ] You should different background images for the mobile version and desktop version in the headline and footer sections. (e.g. `contact form - background-shape-desktop` and `contact form-shapes-mobile`). This will fix the misalignment you are having the background images.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-30 05:32 UTC, henrycode460 commented
Hello sir I'm still waiting on you. I have message you on slack but no
response.

On Fri, Apr 29, 2022, 8:37 AM Tekle Gebreyohannes ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @henrycode460 <https://github.com/henrycode460> 👋 ,
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there! (Please DM me on Slack before you start
> working on this changes)
> Highlights Required Changes ♻️
>
> *Check the comments under the review.*
>
>    -
>
>    I see that you have duplicated your works section HTML code (one for
>    mobile and one for desktop). You should not duplicate your HTML code for
>    different screen sizes. The only thing you need to add is a media query
>    css styling targeting different screen sizes. (min-width: 768px for
>    desktop version in this case)
>    -
>
>    In the works section, it was a requirement to use Flexbox to layout
>    the contents of the project card in the previous milestones. However, you
>    manually swapped the image and project details on every other card instead
>    of using css Flexbox order property. As a result, it is now difficult
>    to make your works section responsive using CSS styling. Please take a look
>    at this
>    <https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Ordering_Flex_Items>
>    tutorial.
>    [image: works-section-800px]
>    <https://user-images.githubusercontent.com/44057863/165910467-880a6f95-c55b-4d6e-907e-23ec8a9d3a85.png>
>    -
>
>    You should different background images for the mobile version and
>    desktop version in the headline and footer sections. (e.g. contact
>    form - background-shape-desktop and contact form-shapes-mobile). This
>    will fix the misalignment you are having the background images.
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> You can also consider:
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In style.css
> <https://github.com/henrycode460/Portfolio-Mobile-Version-Skeleton/pull/5#discussion_r861571617>
> :
>
> > +  padding: 70px 10px;
>
> +  padding: 30px 20px;
>
>
>
>    - You should use padding of padding: 114px 24px; as in the Figma
>    design for mobile version and for the desktop padding: 359px 260px;.
>    This will help you fix the problems as shown in the following snapshots.
>    [image: headline-mob-impl]
>    <https://user-images.githubusercontent.com/44057863/165910031-27a42a88-cb75-4a3b-abd7-7fd95356ec4f.png>
>
> [image: headline-desktop-impl]
> <https://user-images.githubusercontent.com/44057863/165910128-35845191-663d-477f-a8c9-b337ec00fb3d.png>
>
>    - Please add background-repeat: no-repeat; to avoid the repeating
>    background image.
>
> ------------------------------
>
> In style.css
> <https://github.com/henrycode460/Portfolio-Mobile-Version-Skeleton/pull/5#discussion_r861579153>
> :
>
> > +  .langIconDetails {
>
> +    display: flex;
>
> +    flex-direction: column;
>
> +    height: 90px;
>
> +    width: 100px;
>
> +  }
>
>
>
>    - Please add the following to fix the issue you have in the languages
>    section:
>
>      justify-content: space-between;
>
>      align-items: center;
>
>
>
>    - Please also remove the height: 90px;
>    [image: languages-section]
>    <https://user-images.githubusercontent.com/44057863/165911292-c877d444-c8da-4196-86cd-4b3bf8be4e89.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/henrycode460/Portfolio-Mobile-Version-Skeleton/pull/5#pullrequestreview-957409001>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXCDEX7GIXTUONOHZZLGVLTVHONVDANCNFSM5UR6FX2Q>
> .
> You are receiving this because you were mentioned.Message ID:
> <henrycode460/Portfolio-Mobile-Version-Skeleton/pull/5/review/957409001@
> github.com>
>

2022-04-30 05:47 UTC, gtekle commented
Hi @henrycode460 
I am sorry for the inconvenience. May I call you now?

2022-04-30 05:55 UTC, henrycode460 commented
yes please

On Sat, Apr 30, 2022, 5:47 AM Tekle Gebreyohannes ***@***.***>
wrote:

> Hi @henrycode460 <https://github.com/henrycode460>
> I am sorry for the inconvenience. May I call you now?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/henrycode460/Portfolio-Mobile-Version-Skeleton/pull/5#issuecomment-1113924603>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXCDEX6W4N7GXODI2K5F26DVHTCO5ANCNFSM5UR6FX2Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2022-04-30 11:06 UTC, RolandM99 approved these changes
<h1>Status: Approve 🥇 ✔</h1>
Hi @henrycode460, 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

<img src="https://media.giphy.com/media/aNqEFrYVnsS52/giphy.gif" width="100%">

- [ ] [ **OPTIONAL** ] : You're almost there, your project is complete but, It would be better if you center your project card so that the margin-left and margin-right be the same for all screens in the mobile version. Let's rock and fix this simple issue before starting the new week 😃 
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-30 11:27 UTC, merged

2022-10-11 09:20 UTC, henrycode460 commented
I am back , my Internet cable shake

On Fri, Apr 29, 2022, 8:37 AM Tekle Gebreyohannes ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @henrycode460 <https://github.com/henrycode460> 👋 ,
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there! (Please DM me on Slack before you start
> working on this changes)
> Highlights Required Changes ♻️
>
> *Check the comments under the review.*
>
>    -
>
>    I see that you have duplicated your works section HTML code (one for
>    mobile and one for desktop). You should not duplicate your HTML code for
>    different screen sizes. The only thing you need to add is a media query
>    css styling targeting different screen sizes. (min-width: 768px for
>    desktop version in this case)
>    -
>
>    In the works section, it was a requirement to use Flexbox to layout
>    the contents of the project card in the previous milestones. However, you
>    manually swapped the image and project details on every other card instead
>    of using css Flexbox order property. As a result, it is now difficult
>    to make your works section responsive using CSS styling. Please take a look
>    at this
>    <https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Ordering_Flex_Items>
>    tutorial.
>    [image: works-section-800px]
>    <https://user-images.githubusercontent.com/44057863/165910467-880a6f95-c55b-4d6e-907e-23ec8a9d3a85.png>
>    -
>
>    You should different background images for the mobile version and
>    desktop version in the headline and footer sections. (e.g. contact
>    form - background-shape-desktop and contact form-shapes-mobile). This
>    will fix the misalignment you are having the background images.
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> You can also consider:
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In style.css
> <https://github.com/henrycode460/Portfolio-Mobile-Version-Skeleton/pull/5#discussion_r861571617>
> :
>
> > +  padding: 70px 10px;
>
> +  padding: 30px 20px;
>
>
>
>    - You should use padding of padding: 114px 24px; as in the Figma
>    design for mobile version and for the desktop padding: 359px 260px;.
>    This will help you fix the problems as shown in the following snapshots.
>    [image: headline-mob-impl]
>    <https://user-images.githubusercontent.com/44057863/165910031-27a42a88-cb75-4a3b-abd7-7fd95356ec4f.png>
>
> [image: headline-desktop-impl]
> <https://user-images.githubusercontent.com/44057863/165910128-35845191-663d-477f-a8c9-b337ec00fb3d.png>
>
>    - Please add background-repeat: no-repeat; to avoid the repeating
>    background image.
>
> ------------------------------
>
> In style.css
> <https://github.com/henrycode460/Portfolio-Mobile-Version-Skeleton/pull/5#discussion_r861579153>
> :
>
> > +  .langIconDetails {
>
> +    display: flex;
>
> +    flex-direction: column;
>
> +    height: 90px;
>
> +    width: 100px;
>
> +  }
>
>
>
>    - Please add the following to fix the issue you have in the languages
>    section:
>
>      justify-content: space-between;
>
>      align-items: center;
>
>
>
>    - Please also remove the height: 90px;
>    [image: languages-section]
>    <https://user-images.githubusercontent.com/44057863/165911292-c877d444-c8da-4196-86cd-4b3bf8be4e89.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/henrycode460/Portfolio-Mobile-Version-Skeleton/pull/5#pullrequestreview-957409001>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXCDEX7GIXTUONOHZZLGVLTVHONVDANCNFSM5UR6FX2Q>
> .
> You are receiving this because you were mentioned.Message ID:
> <henrycode460/Portfolio-Mobile-Version-Skeleton/pull/5/review/957409001@
> github.com>
>